name: lakehouse
version: "1.0.0"
config-version: 2
profile: lakehouse

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  lakehouse:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
